-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."users"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    "email" character varying(100) NOT NULL,
    "password" character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."candidates"
(
    "user_id" integer,
    "first_name" character varying(50) NOT NULL,
    "last_name" character varying(50) NOT NULL,
    "national_identity" character varying(11) UNIQUE,
    "date_of_birth" date NOT NULL
);

CREATE TABLE public."employers"
(
    "user_id" integer,
    "company_name" character varying(50) NOT NULL,
    "web_address" character varying(50) NOT NULL,
    "phone_number " character varying(50) NOT NULL
);

CREATE TABLE public."employees"
(
    "user_id" integer,
    "first_name" character varying(50) NOT NULL,
    "last_name" character varying(50) NOT NULL
);

CREATE TABLE public."job_positions"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    name character varying(50) UNIQUE,
    PRIMARY KEY (id)
);

CREATE TABLE public."cities"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    name character varying(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."job_advertisements"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    job_position_id integer NOT NULL,
	city_id integer NOT NULL,
	employer_id integer NOT NULL,
	job_detail character varying(250) NOT NULL,
	min_salary money NOT NULL,
	max_salary money NOT NULL,
	open_position integer NOT NULL,
	create_date date NOT NULL,
	deadline date NOT NULL,
	status BOOLEAN NOT NULL,
	
    PRIMARY KEY (id)
);
CREATE TABLE public."resumes"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
	"photo" character varying(100) NOT NULL,
    "github" character varying(100) NOT NULL,
	"linkedin" character varying(100) NOT NULL,
	"cover_letter" character varying(200) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."educations"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    "resume_id" integer,
	"high_school" character varying(100) NOT NULL,
    "university" character varying(100) NOT NULL,
	"department" character varying(100) NOT NULL,
	"graduate" BOOLEAN NOT NULL,
	"star_of_year" date NOT NULL,
	"finish_of_year" date NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."skills"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
	"resume_id" integer,
	"name" character varying(100) NOT NULL,
  
    PRIMARY KEY (id)
);

CREATE TABLE public."languages"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
	"resume_id" integer,
	"name" character varying(100) NOT NULL,
    "level" character varying(100) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."experiences"
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 MINVALUE 1 MAXVALUE 9999999 CACHE 1 ),
    "resume_id" integer,
	"workplace_name" character varying(100) NOT NULL,
    "position" character varying(100) NOT NULL,
	"still_work" BOOLEAN NOT NULL,
	"start_of_work" date NOT NULL,
	"finish_of_work" date NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public."resumes"
    ADD FOREIGN KEY ("candidate_user_id")
    REFERENCES public."users" (id)
    NOT VALID;	

ALTER TABLE public."educations"
    ADD FOREIGN KEY ("resume_id")
    REFERENCES public."resumes" (id)
    NOT VALID;
	
ALTER TABLE public."skills"
    ADD FOREIGN KEY ("resume_id")
    REFERENCES public."resumes" (id)
    NOT VALID;

ALTER TABLE public."languages"
    ADD FOREIGN KEY ("resume_id")
    REFERENCES public."resumes" (id)
    NOT VALID;
	
ALTER TABLE public."experiences"
    ADD FOREIGN KEY ("resume_id")
    REFERENCES public."resumes" (id)
    NOT VALID;	
ALTER TABLE public."job_advertisements"
    ADD FOREIGN KEY ("employer_id")
    REFERENCES public."users" (id)
    NOT VALID;

ALTER TABLE public."job_advertisements"
    ADD FOREIGN KEY ("city_id")
    REFERENCES public."cities" (id)
    NOT VALID;
	
ALTER TABLE public."job_advertisements"
    ADD FOREIGN KEY ("job_position_id")
    REFERENCES public."job_positions" (id)
    NOT VALID;	


ALTER TABLE public."candidates"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" (id)
    NOT VALID;


ALTER TABLE public."employers"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" (id)
    NOT VALID;
	
ALTER TABLE public."employees"
    ADD FOREIGN KEY ("user_id")
    REFERENCES public."users" (id)
    NOT VALID;

END;